/* eslint-disable @next/next/link-passhref */
import React from "react";
import Head from "next/head";
import * as style from "@/styles/document.module.css";
import FootV1 from "@/components/footer/footv1";
import Link from "next/link";
import HeadV2 from "@/components/header/headv2";
import NavigationV2 from "@/components/navigation/navigationv2";
import LinksButton from "@/components/caveats/links";
export default function Disclaimer() {
  return (
    <div className={style.main}>
      <Head>
        <title>RCK - Disclaimer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HeadV2 title={"Documentation"} root={"/v1"} />
      <div className={style.titleContainer}>
        <h2 className={style.titleText}>Disclaimer</h2>
      </div>
      <div className={style.container}>
        <NavigationV2 />

        <div className={style.contentBox}>
          <p className={style.normalText}>
            <b>
              READ AND UNDERSTAND BEFORE PURCHASING RCK TOKENS OR ACCESSING ANY
              RCK VENTURE PLATFORM SUCH AS THE RPS NFT GAME
            </b>
          </p>
          <p className={style.normalText}>
            THIS RCK WHITE PAPER (“WHITE PAPER”) IS INTENDED TO PROVIDE THE
            READER WITH INFORMATION REGARDING RCK TOKENS, RPS NFT GAME (“RPS”)
            AND ITS PLANS FOR THE PLATFORM. IT IS ONLY MEANT TO INFORM THE
            PLANNED VENTURES, DESIGN AND OVERALL IDEA OF THE RPS, RCK TOKENS AS
            WELL AS THE FUTURE PROJECTS, CALLED VENTURES.
          </p>
          <p className={style.normalText}>
            THIS WHITE PAPER IS FOR INFORMATION PURPOSES ONLY AND{" "}
            <b>
              <u> DOES NOT</u>{" "}
            </b>{" "}
            REPRESENT A COMMITMENT TO YOU, THE READER, OF ANY OF THE CURRENT OR
            FUTURE DESIGNS OR FUNCTIONALITY OF THE RPS NFT, RCK TOKEN AND/OR ITS
            FUTURE RCK VENTURES
          </p>

          <p className={style.normalText}>
            THIS WHITE PAPER{" "}
            <b>
              <u> IS NOT AND MUST NOT BE </u>
            </b>{" "}
            CONSTRUED AS A SOLICITATION TO PURCHASE RCK TOKENS. PURCHASING RCK
            TOKENS INVOLVES CONSIDERABLE RISK. THE TOKEN MAY BECOME WORTHLESS
            THEREBY INCURRING SIGNIFICANT OR TOTAL LOSS OF VALUE. NO PURCHASES
            CAN BE REFUNDED OR EXCHANGED. MOREOVER, DO NOT PURCHASE THE RCK
            TOKENS WITH MONEY YOU CANNOT AFFORD TO LOSE.
          </p>

          <p className={style.normalText}>
            ADDITIONALLY, RPS NFT GAMES AND ITS PLATFORM MAY{" "}
            <b>
              <u> NOT MEET </u>
            </b>{" "}
            YOUR NEEDS. THERE IS NO GUARANTEE THAT THE UTILITY OF RCK TOKENS
            WILL MEET YOUR NEEDS OR EXPECTATIONS, CURRENTLY OR IN THE FUTURE.
          </p>

          <p className={style.normalText}>
            RCK TOKENS{" "}
            <b>
              <u> ARE NOT </u>
            </b>{" "}
            SHARES OF A COMPANY OR SECURITIES OF ANY TYPE. THEY{" "}
            <b>
              <u> DO NOT </u>
            </b>
            GRANT OR VEST UNTO THE HOLDER ANY KIND OF OWNERSHIP OR OTHER
            INTEREST IN ANY COMPANY. THE RCK TOKEN IS PLANNED TO FACILITATE THE
            USER OF RPS NFT GAMES AND OTHER POTENTIAL VENTURES. THEY{" "}
            <b>
              <u> ARE NOT </u>
            </b>{" "}
            INVESTMENTS; THERE IS NO PROMISE THAT THEY WILL INCREASE IN VALUE;
            THEY ARE VALUABLE ONLY INSOFAR AS THEY ARE DESIGNED TO FUNCTION
            WITHIN RPS NFT GAMES AND OTHER RCK VENTURES.
          </p>

          <p className={style.normalText}>
            SHOULD YOU PURCHASE RCK TOKENS, YOU INHERENTLY AND WITH FULL
            KNOWLEDGE, ASSUME THE RISK OF ITS LOSS OF VALUE FROM THE TIME OF
            PURCHASE. FURTHERMORE, BY PURCHASING RCK TOKENS, YOU ARE AGREEING
            THAT THE TOKENS’ PRESENT FUNCTIONALITY MIGHT BE ALL THEY ARE EVER
            CAPABLE OF DOING AND ITS VALUE POTENTIALLY RENDER WORTHLESS.
            THEREFORE, HAVING FULL KNOWLEDGE AND AWARENESS OF THE ABOVE, IF YOU
            PURCHASE ANY OF RCK TOKEN, YOU AGREE THAT YOU HAVE NO RECOURSE AND
            YOU WILL NOT ASSERT ANY CLAIM, ACTION, JUDGEMENT OR REMEDY AGAINST
            RPS NFT GAMES, ITS PROGRAMMERS, SPONSORS, COMMUNITY CO-FOUNDERS AND
            RELATED PARTIES IF THE RCK TOKEN LOSES VALUE, THE RPS NFT GAME
            PLATFORM OR NETWORK CEASES TO FUNCTION, OR IF THE FUTURE PLANS
            (VENTURES) DO NOT ULTIMATELY MEET YOUR INTENDED REQUIREMENTS OR
            EXPECTATIONS. IF YOU ARE UNCERTAIN WHETHER TO PURCHASE RCK TOKENS IN
            LIGHT OF THESE DISCLAIMERS HEREIN, OR IF YOU ARE CONCERNED ABOUT THE
            LOSS OF ANY MONEY YOU USE TO PURCHASE THE RCK TOKENS,{" "}
            <b>
              <u>WE STRONGLY URGE YOU NOT TO PURCHASE ANY RCK TOKENS.</u>
            </b>
          </p>

          <p className={style.normalText}>
            WE STRONGLY RECOMMEND YOU TO CONSULT LEGAL, FINANCIAL, TAX, AND
            OTHER PROFESSIONAL ADVISORS OR EXPERTS FOR FURTHER GUIDANCE BEFORE
            PURCHASING THE TOKENS. WE CANNOT PROVIDE YOU ANY OF THE FOREGOING
            ADVICE.
          </p>
          <div className={style.previewContainer}>
            <Link href="/">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>Homepage</h4>
              </div>
            </Link>

            <Link href="/v1/rpsnftgame">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>RPS NFT Game</h4>
              </div>
            </Link>
          </div>
          <LinksButton />
        </div>
      </div>

      <FootV1 />
    </div>
  );
}
