/* eslint-disable @next/next/link-passhref */
import React from 'react'
import Head from 'next/head'
import * as style from '@/styles/document.module.css'
import FootV1 from '@/components/footer/footv1';
import Link from 'next/link'
import HeadV2 from '@/components/header/headv2'
import NavigationV2 from '@/components/navigation/navigationv2';
import LinksButton from '@/components/caveats/links';

export default function Disclaimer() {
  

  return (
    <div className={style.main}>
      <Head>
        <title>RCK - ROADMAP</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <HeadV2 title={"Documentation"} root={"/v1"}/>
      <div className={style.titleContainer}>
        <h2 className={style.titleText} >Forward Looking</h2>
      </div>
      <div className={style.container}>
        <NavigationV2/>

        

        <div className={style.contentBox}>
          <h2 className={style.headlineText}>
            Venture with us!
          </h2>
          <p className={style.normalText}>
            This is RCK's strategic plan defining the goal or desired outcome and major steps or milestones needed to reach it. 
          </p>
          <h3 className={style.title2Text}>
            STAGE 1 - Q2 2021
          </h3>
          <div className={style.imageBox1}>
            <img src="/Images/roadmap/Slide1.JPG" className={style.image1}/>
          </div>
         
          <p className={style.listText}>• Brainstorming concept and identity development </p>
          <p className={style.listText}>  • Research and incubation of Venture 1 </p>
          <p className={style.listText}>  • Testing of V1 RPS NFT Game </p>
          <p className={style.listText}> • White Paper development </p>
          <p className={style.listText}> • Website development </p>
          <p className={style.listText}> • Team formation </p>
          <p className={style.listText}> • Idea dissemination to interested people for future Roadshows and Initial Public Distribution
         
          <div className={style.dash}/>

          <h3 className={style.title2Text}>
            STAGE 2 - Q4 2021
          </h3>
          <div className={style.imageBox1}>
            <img src="/Images/roadmap/Slide2.JPG" className={style.image1}/>
          </div>
            <p className={style.listText}>• Whitepaper Release</p>
            <p className={style.listText}> • Website Launch –</p>
            <p className={style.listText}> • Launch for Venture 1: RPS NFT Game </p>
            <p className={style.listText}>•  Roadshows For Initial Private Distribution (IPD) of RCK Tokens</p>
            <p className={style.listText}>• Initial Distribution of Axesscards NFT</p>
            <p className={style.listText}> • Public Launching of RCK Tokens</p>
            <p className={style.listText}>• Early Adopter Allocation - tentative</p>
        

          <div className={style.dash}/>


          <h3 className={style.title2Text}>
            STAGE 3 - Q2 2022
          </h3>
         
          <div className={style.imageBox1}>
            <img src="/Images/roadmap/Slide3.JPG" className={style.image1}/>
          </div>
              <p className={style.listText}> RCK Listing on Decentralized Exchange (DEX) </p>
              <p className={style.listText}>• 1 st Enhancement V1 RPS NFT Game</p>
              <p className={style.tab2Text}>
              - Launch RPS Marketplace<br/>
              - Beta Testing RPS to Android<br/>
              </p>  
              <p className={style.listText}> Incubation of Venture 2 (V2)</p>
      
           </p>


           <div className={style.dash}/>
           <p className={style.subText2}>
          </p>

           <h3 className={style.title2Text}>
            STAGE 4 - Q1 2023
          </h3>
          <p className={style.labelText}>
           
          </p>
          <div className={style.imageBox1}>
            <img src="/Images/roadmap/Slide4.JPG" className={style.image1}/>
          </div>
          
          <p className={style.listText}>• V1 RPS NFT Game - 2nd Enhancement</p>
              <p className={style.tab2Text}>
              - Beta Testing RPS to IOS<br/>
              - Launch of RPS to Android<br/>
              </p>
              <p className={style.listText}> • V2 Beta Testing</p>
              <p className={style.listText}>• Marketing and Partnerships for Ventures</p>

           <div className={style.dash}/>


          <h3 className={style.title2Text}>
            STAGE 5 - Q4  2022
          </h3>
          <div className={style.imageBox1}>
            <img src="/Images/roadmap/Slide5.JPG" className={style.image1}/>
          </div>
         
          <p className={style.listText}>• V1 RPS NFT Game - 3rd Enhancement</p>
            <p className={style.tab2Text}>
            - Development to native platform<br/>
            </p>
            <p className={style.listText}>• V2 Launching</p>
            <p className={style.listText}>• Incubation of Venture 3 (V3) – Marketplace</p>
            <p className={style.listText}>• Additional Listing</p>

         

        <div className={style.dash}/>

          <h3 className={style.title2Text}>
            STAGE 6 - Q3 2022
          </h3>
          <div className={style.imageBox1}>
            <img src="/Images/roadmap/Slide6.JPG" className={style.image1}/>
          </div>
         
          <p className={style.listText}>• V3 Beta Testing and Launching </p>
          <p className={style.listText}> • Expansion of ventures with additional applications</p>
          <p className={style.listText}> • Additional Listing on other DEX (Coinmarketcap and Coingecko) </p>
         




          
          <div className={style.previewContainer}>
            
            <Link href="/v1/initialfundsanduse">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>Target Funds and Uses</h4> 
              </div>
            </Link>
              
            <Link href="/">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>Homepage</h4> 
              </div>
            </Link>

          </div>
          <LinksButton/>
        </div>

      </div>

      <FootV1/>
    </div>
  )
}
