/* eslint-disable @next/next/link-passhref */
import React from "react";
import Head from "next/head";
import * as style from "@/styles/document.module.css";
import FootV1 from "@/components/footer/footv1";
import Link from "next/link";
import HeadV2 from "@/components/header/headv2";
import NavigationV2 from "@/components/navigation/navigationv2";
import LinksButton from "@/components/caveats/links";

export default function Disclaimer() {
  return (
    <div className={style.main}>
      <Head>
        <title>RCK - Our Vision to Venture</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Head>
        <title>RCK•ROCK Token - The RCK Ventures</title>
        <meta
          name="description"
          content="“RCK Ventures” are projects that harness blockchain technology. These are envisioned to increase users, utilization, activities and therefore expand the RCK ecosystem."
        />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="RCK•ROCK Token - The RCK Ventures" />
        <meta
          property="og:description"
          content="“RCK Ventures” are projects that harness blockchain technology. These are envisioned to increase users, utilization, activities and therefore expand the RCK ecosystem."
        />
        <meta property="og:image" content="./Images/ventures/Slide1.JPG" />
      </Head>
      <HeadV2 title={"Documentation"} root={"/v1"} />
      <div className={style.titleContainer}>
        <h2 className={style.titleText}>The RCK Ventures</h2>
      </div>
      <div className={style.container}>
        <NavigationV2 />

        <div className={style.contentBox}>
          <h2 className={style.headlineText}>"The RCK Utilization Value"</h2>
          <p className={style.normalText}>
            “Ventures” are projects that harness blockchain technology. These
            are envisioned to increase users, utilization, activities and
            therefore expand the RCK ecosystem. In doing so, RCK’s value, as a
            utility token, also strengthens driven by utilization across these
            Ventures. These Ventures could be around Gaming, NFT Marketplace,
            DeFi and so on…
          </p>
          <div className={style.imageBox1}>
            <img src="/Images/ventures/Slide1.JPG" className={style.image1} />
          </div>

          <h3 className={style.title2Text}>Venture 1 - RPS Game [developed]</h3>
          <div className={style.imageBox1}>
            <img src="/Images/ventures/Slide2.JPG" className={style.image1} />
          </div>
          <p className={style.normalText}>
            This simple and very basic game will be the primary introduction for
            the Rock Ventures and RCK Token. So, we strategically launched it as
            the gateway especially for inexperienced and unfamiliar users to the
            blockchain technology. However, this simple game already
            incorporates the use of NFTs as the Axess Cards to play, earn
            rewards and trade!
          </p>

          <h3 className={style.title2Text}>
            Venture 2 - Game [To be developed]
          </h3>
          <div className={style.imageBox1}>
            <img src="/Images/ventures/Slide3.JPG" className={style.image1} />
          </div>
          <p className={style.normalText}>
            As the RPS Game is designed for mass adoption with basic concept and
            functionality, another game is envisioned with more sophistication
            to attract gamers.
          </p>

          <h3 className={style.title2Text}>
            Venture 3 - NFT Marketplace [To be developed]
          </h3>
          <div className={style.imageBox1}>
            <img src="/Images/ventures/Slide4.JPG" className={style.image1} />
          </div>
          <p className={style.normalText}>
            A marketplace for buying, selling and trading NFTs. It will open a
            whole new world to RCK users. This makes sense as it integrates
            communities using the RPS Game’s collectible Axess Cards and
            ofcourse, other digital assets all over the world. The NFT
            Marketplace will not just be limited to “artist”, celebrities and
            the famous, but anyone can buy or sell their NFTs!
          </p>

          <h3 className={style.title2Text}>Venture 4 and so on …</h3>
          <div className={style.imageBox1}>
            <img src="/Images/ventures/Slide5.JPG" className={style.image1} />
          </div>
          <p className={style.normalText}>
            Decentralized Finance Platforms (DeFi) [To be developed]
          </p>

          <div className={style.previewContainer}>
            <Link href="/v1/abstractandbackdrop">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>Abstract And Backdrop</h4>
              </div>
            </Link>

            <Link href="/v1/rpsnftgame">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>RPS NFT GAME</h4>
              </div>
            </Link>
          </div>
          <LinksButton />
        </div>
      </div>

      <FootV1 />
    </div>
  );
}
